export const permission = {
  editPublication: 'editPublication',
  createPublication: 'editPublication',
  createIssue: 'createIssue',
  editIssue: 'editIssue',
  removeIssue: 'removeIssue',
  manageManagingEditors: 'manageManagingEditors',
  manageEditors: 'manageEditors',
  manageContributors: 'manageContributors',
  manageAdvertisers: 'manageAdvertisers',
  viewContributions: 'viewContributions',
  viewAdvertisements: 'viewAdvertisements',
  addMembers: 'addMembers',
  deleteMembers: 'deleteMembers',
  publishingFlow: 'publishingFlow',
  hasPermissionManagingEditor: 'hasPermissionManagingEditor',
  fundraisingViewPreview: 'fundraisingViewPreview',
  fundraisingSendInvites: 'fundraisingSendInvites',
  fundraisingReport: 'fundraisingReport',
  fundraisingViewLevels: 'fundraisingLevels',
  fundraisingCreateLevel: 'fundraisingCreateLevel',
  transfers: 'transfers',
  advertising: 'advertising',
  advertisingMatrix: 'advertisingMatrix',
  advertisingReport: 'advertisingReport',
  advertisingResources: 'advertisingResources',
  advertisingInvites: 'advertisingInvites',
  canEditShare: 'canEditShare',
  canManageInvoices: 'canManageInvoices',
};

export enum permissionEnum {
  editPublication = 'editPublication',
  createPublication = 'editPublication',
  createIssue = 'createIssue',
  editIssue = 'editIssue',
  removeIssue = 'removeIssue',
  manageManagingEditors = 'manageManagingEditors',
  manageEditors = 'manageEditors',
  manageContributors = 'manageContributors',
  manageAdvertisers = 'manageAdvertisers',
  viewContributions = 'viewContributions',
  viewAdvertisements = 'viewAdvertisements',
  addMembers = 'addMembers',
  deleteMembers = 'deleteMembers',
  publishingFlow = 'publishingFlow',
  hasPermissionManagingEditor = 'hasPermissionManagingEditor',
  fundraisingViewPreview = 'fundraisingViewPreview',
  fundraisingSendInvites = 'fundraisingSendInvites',
  fundraisingReport = 'fundraisingReport',
  fundraisingViewLevels = 'fundraisingLevels',
  fundraisingCreateLevel = 'fundraisingCreateLevel',
  transfers = 'transfers',
  advertising = 'advertising',
  advertisingMatrix = 'advertisingMatrix',
  advertisingReport = 'advertisingReport',
  advertisingResources = 'advertisingResources',
  advertisingInvites = 'advertisingInvites',
  canEditShare = 'canEditShare',
  canManageInvoices = 'canManageInvoices',
}
